# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google',
            name='user',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
    ]
