# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 06:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20180728_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_asker', models.CharField(max_length=50, verbose_name='Can I have your name, genius?')),
                ('content', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('asking_day', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_user_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ahihi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
